import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/3.Footer/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-white">
        <div className="flex flex-col gap-10">
          <div className="w-full">
            {" "}
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
